version: '3'

services:
  nginx:
    build:
      context: ./nginx  
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - mysql

  php:
    build:
      context: ./php  
    volumes:
      - ./php:/var/www/html

  mysql:
    build:
      context: ./mysql  
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
